### ISSUE TITLE
Test grammar throws an exception

### ISSUE THREAD

**Issue by halesfi** [spetitjean/TuLiPA-frames#15]
I am running [TuLiPA-frames](https://github.com/spetitjean/TuLiPA-frames) on Ubuntu Linux 22.04. When running as `./run/test.sh`, entering a sentence `John loves Mary` and clicking _Parse_, the result is an exception:
```
java.lang.NullPointerException
	at de.duesseldorf.io.XMLTypeHierarchyReader.getHierarchyConstraintsfromNL(XMLTypeHierarchyReader.java:290)
	at de.duesseldorf.io.XMLTypeHierarchyReader.getTypeHierarchy(XMLTypeHierarchyReader.java:84)
	at de.duesseldorf.ui.WorkbenchLoader.loadSituation(WorkbenchLoader.java:259)
	at de.tuebingen.ui.InputGUI.doParse(InputGUI.java:886)
	at de.tuebingen.ui.InputGUI$ParseLauncher.run(InputGUI.java:927)
```

**Comment by spetitjean** [comment]
Hi! 
Thanks for pointing that out, there was a recent update of format in the file storing the type hierarchy, and this example uses the old format.
It should now (commit b87b367) display a warning instead of crashing. I will try to update the examples at some point (this one does not use advanced constraints on types as far as I know).

**Comment by halesfi** [comment]
Great, thank you, the test example works now.
